CREATE TABle resturants(id INTEGER Primary Key AUTOINCREMENT, name STRING, speciality STRING, location STRING);

INSERT INTO resturants (name, speciality, location) VALUES("Kenya's Keto Kitchen", "Keto", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Dirty Root", "Low Carb", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("CRAFT Donuts + Coffee", "Keto", "Chicago");
INSERT INTO resturants (name, speciality, location) VALUES("Tweet", "Low Carb", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("The Eating Well", "Vegan", "Schaumburg, IL");
INSERT INTO resturants (name, speciality, location) VALUES("True Food Kitchen", "Vegan", "Oak Brook, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Kale My Name", "Vegan", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("The Water Bar", "Gluten Free", "Geneva, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Alice and Friends Vegan Kitchen", "Vegan", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Victus Foods", "Paleo", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("THAI GARDEN", "Paleo", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Protien Bar and Kitchen", "Low Carb", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Purple Sprout Concious Organic", "Vegan", "Buffalo Grove, IL");
INSERT INTO resturants (name, speciality, location) VALUES("LYFE Kitchen", "Vegan", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Fittingly Delicious", "Low Carb", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Harvest Room", "Vegan", "Palos Heights, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Sweet Natalies Gluten Free Bakery/Baby Doll Bakery", "Gluten Free", "Wheaton, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Da Luciano's", "Gluten Free", "Rivers Grove");
INSERT INTO resturants (name, speciality, location) VALUES("Wheat's End Cafe & Bakery", "Gluten Free", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Maggiano's Little Italy", "Gluten Free", "Schaumburg, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Moretti's", "Gluten Free", "Bartlett, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Augustino's Rock and Roll Deli and Grill
", "Gluten Free", "Carol Stream");
INSERT INTO resturants (name, speciality, location) VALUES("Nature's Best Cafe", "Vegan", "Naperville, IL");
INSERT INTO resturants (name, speciality, location) VALUES("sweetgreen", "Low Protien", "Schaumburg");
INSERT INTO resturants (name, speciality, location) VALUES("Low Carb Kitchen", "Low Carb", "Downers Grove, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Egg Harbor Cafe", "Gluten Free", "Naperville, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Panera Bread", "Keto", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Panera Bread", "Keto", "Berwyn, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Panera Bread", "Keto", "River Forest, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Panera Bread", "Keto", "Emlwood Park, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Panera Bread", "Keto", "Norridge, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Panera Bread", "Keto", "Oak Lawn, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Taco Bell", "Keto", "Chicago, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Taco Bell", "Keto", "Hanover Park, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Taco Bell", "Keto", "Addison, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Taco Bell", "Keto", "Aurora, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Chili's Grill & Bar", "Keto", "Aurora, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Chili's Grill & Bar", "Keto", "Bolingbrook, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Chili's Grill & Bar", "Keto", "Naperville, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Chili's Grill & Bar", "Keto", "Oswego, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Chili's Grill & Bar", "Keto", "Plainfield, IL");
INSERT INTO resturants (name, speciality, location) VALUES("Chili's Grill & Bar", "Keto", "Batavia, IL");